name: secure_video_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  mongo_dart: ^0.10.0
  file_picker: ^5.0.0
  provider: ^6.0.2
  crypto: ^3.0.1
  encrypt: ^5.0.0
  pdf: ^3.6.5
  advance_pdf_viewer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.webp
